openapi: 3.0.0
info:
  title: AutoService API
  description: API para gestionar autos.
  version: 1.0.0
servers:
  - url: http://localhost:8080/prueba/rs
paths:
  /Autos:
    post:
      summary: Crear un nuevo auto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto'
      responses:
        '200':
          description: Auto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      summary: Actualizar un auto existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auto'
      responses:
        '200':
          description: Auto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auto'
        '404':
          description: Auto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Eliminar un auto
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Auto eliminado exitosamente
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Error al eliminar el auto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /Autos/lista:
    get:
      summary: Obtener la lista de autos
      responses:
        '200':
          description: Lista de autos obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auto'
        '404':
          description: No hay autos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    Auto:
      type: object
      properties:
        id:
          type: integer
        marca:
          type: string
        placa:
          type: string
        precio:
          type: number
    ErrorMessage:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
